name: scheduled_notifications

version: 1.0.0
description: A flutter plugin for scheduling notifications on Android.
author: Tobias Westergaard Kjeldsen<tobias@wkjeldsen.dk>
homepage: https://github.com/Tobiaswk/scheduled_notifications

flutter:
  plugin:
    androidPackage: dk.kjeldsen.scheduled_notifications
    pluginClass: ScheduledNotificationsPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
